version: "3"
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "username"
      DB_MYSQL_PASSWORD: "password"
      DB_MYSQL_NAME: "username"
    volumes:
      - /home/sam/docker/nginx-proxy-manager/data:/data
      - /home/sam/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      - frontend
    restart: unless-stopped
    logging:
      driver: "gelf"
      
networks:
  frontend:
    external: true
