---
version: "2.1"
services:
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /volume1/DOCKER/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
