---
version: "2.1"
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/sam/docker/radarr:/config
      - /mnt/ssd2/media/media/movies:/movies
      - /mnt/ssd2/media/torrents/movies:/downloads
    networks:
      - backend
    ports:
      - 7878:7878
    restart: unless-stopped
    logging:
      driver: "gelf"
      
networks:
  backend:
    external: true
