---
version: "2.1"
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /volume1/DOCKER/radarr:/config
      - /volume1/MEDIA/media/movies:/movies
      - /volume1/MEDIA/torrents:/downloads
    networks:
      - backend
    ports:
      - 7878:7878
    restart: unless-stopped
