version: '3.3'
services:
  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=uk_london
      - OPENVPN_USERNAME=p0628314
      - OPENVPN_PASSWORD=Sam,McNab1.1
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=10.10.0.0/16
      - CREATE_TUN_DEVICE=true
      - TZ=Europe/London
      - TRANSMISSION_WEB_UI=combustion
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - PUID=1000
      - PGID=1000
    volumes:
      - '/mnt/ssd2/media/torrents:/data'
      - '/home/sam/docker/qbittorrent:/config'
    ports:
      - '9091:9091'
    networks:
      - openvpn
      - backend
    cap_add:
      - NET_ADMIN
    restart: always
    logging:
      driver: "gelf"
      
networks:
  openvpn:
    external: true
  backend:
    external: true
