version: "3"
services:
  pialert:
    container_name: pi-alert
    image: "jokobsk/pi.alert:latest"  
    environment:
      - TZ=Europe/London
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211
    volumes:
      - /home/sam/docker/pialert/config:/home/pi/pialert/config
      - /home/sam/docker/pialert/db:/home/pi/pialert/db
      - /home/sam/docker/pialert/db/setting_darkmode:/home/pi/pialert/db/setting_darkmode
      - /home/sam/docker/pialert/logs:/home/pi/pialert/log
    ports:
      - "80:20211/tcp"
    network_mode: "host"        
    restart: unless-stopped
    logging:
      driver: "gelf"
