---
version: "2.1"
services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /volume1/DOCKER/sonarr:/config
      - /volume1/MEDIA/media/tv:/tv
      - /volume1/MEDIA/torrents:/downloads
    ports:
      - 8989:8989
    networks:
      - backend
    restart: unless-stopped