version: '3'
services:
    node-red:
      container_name: node-red
      image: nodered/node-red
      environment:
        - REDBOT_ENABLE_MISSION_CONTROL=true
      volumes:
        - '/home/sam/docker/node-red:/data' 
      ports:
        - '1880:1880'
      networks:
        - frontend
      restart: unless-stopped
      logging:
        driver: "gelf"
  
networks:
  frontend:
    external: true
