version: '3'
services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
    volumes:
      - /home/sam/docker/jellyseerr:/app/config
    ports:
      - 5055:5055
    networks:
      - frontend
    restart: unless-stopped
    logging:
      driver: "gelf"
      
networks:
  frontend:
    external: true
