---
version: "2"
services:
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/sam/docker/nextcloud/config:/config
      - /mnt/ssd1/files:/data
    ports:
      - 443:443
    networks:
      - frontend
      - backend
    restart: unless-stopped
    logging:
      driver: "gelf"
      
networks:
  frontend:
    external: true
  backend:
    external: true
